### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by ali1234** [flathub/com.jetbrains.CLion#16]
1. Start CLion flatpak
2. Open the terminal
3. `ls /usr/lib/x86_64-linux-gnu/`

Expected result:

I should see all the libraries installed on the host.

Actual result:

I only see a small selection of libraries included in the flatpak.

This prevents building pretty much anything. For example, the following trivial CMakeLIsts.txt will fail to build in the flatpak:

```
cmake_minimum_required(VERSION 3.7)
project(SDL2Test)
find_package(SDL2 REQUIRED)
add_executable(SDL2Test Main.cpp)
if(TARGET SDL2::SDL2)
    set(SDL2_LIBRARIES SDL2::SDL2main SDL2::SDL2)
endif()
target_include_directories(SDL2Test PRIVATE ${SDL2_INCLUDE_DIRS})
target_link_libraries(SDL2Test ${SDL2_LIBRARIES})
```

With the following Main.cpp:

```
#include "SDL.h"

int main(int argc, char *argv[])
{
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Quit();
  return 0;
}
```

This project builds correctly outside flatpak. It also builds correctly using the CLion snap.

**Comment by ali1234** [comment]
This problem also extends to build tools. For example:

```
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/arm-none-eabi-g++

  is not a full path to an existing compiler tool.
```

**Comment by binaryfields** [comment]
System libraries and tools are provided by org.freedesktop.Sdk runtime. Any libraries not provided by the runtime need to be added as source dependencies. This is currently limitation of the distribution model. 

I think there is ongoing work to add support for toolbox containers to flatpak IDE applications which would allow you to add/expose arbitrary packages/libraries to your IDE. I would follow flatpak/toolbox updates from Christian Schaller (https://blogs.gnome.org/uraeus/) to see updates on the ongoing work.
