### ISSUE TITLE
Cannot access svn client

### ISSUE THREAD

**Issue by osmeest** [flathub/com.jetbrains.CLion#27]
Quite strangely, CLion can access git (found in /usr/bin) but not svn although it is installed in the very same directory.
This is annoying.

Accessing through /var/run/host does not work (access to dynamic linked libs fails).

**Comment by binaryfields** [comment]
CLion is based on FreeDesktop SDK 21.08. SVN does not appear to be offered as part of that runtime. 

```
sh-5.1$ find /usr -name git
/usr/bin/git
/usr/lib/i386-linux-gnu/ruby/3.0.0/bundler/source/git
/usr/lib/x86_64-linux-gnu/ruby/3.0.0/bundler/source/git
/usr/libexec/git-core/git
sh-5.1$ find /usr -name svn
sh-5.1$ 
``` 

If you need SVN or any other tool that do not come with the runtime, you would need to build it manually from within the sand-boxed CLion process.
