### ISSUE TITLE
FATAL:setuid_sandbox_host.cc(157)

### ISSUE THREAD

**Issue by motorto** [flathub/com.jetbrains.CLion#43]
After updating today the Clion closes with the following error:

```
[0330/130605.810353:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/clion/jbr/lib/chrome-sandbox is owned by root and has mode 4755.
```

reverting: `sudo flatpak update --commit=9984a98efec63a51c75f5c31edd30a45e49dd14847de77105e880a7d9b55cb25 com.jetbrains.CLion`

Solves the issue

**Comment by binaryfields** [comment]
Thank you for reporting the issue. I reverted the latest commit.

**Comment by motorto** [comment]
Should I close the issue or lets keep it open, until a working update
its done ?

**Comment by motorto** [comment]
@binaryfields  just a heads up everyone currently installing Clion trough flatpak will get the version with this error.

**Comment by binaryfields** [comment]
@motorto  The commit with the revert (16e9ec5) should be pushed to flathub soon and overwrite the previous/broken release so I expect that once that happens, everyone will be able to get/upgrade to working release again.

**Comment by FakeShemp** [comment]
The new Chromium sandbox needs zypak. See here for fix: https://github.com/flathub/com.jetbrains.PyCharm-Community/pull/534

**Comment by appelgriebsch** [comment]
Looks like zypak produces side-effects (e.g. git no longer working properly). I just found a couple of fixes that has been made recently in the IDEA flatpak repo and moved them over. My initial tests look good so far.
https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/issues/137, https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/pull/139
