### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by leqord** [flathub/com.jetbrains.CLion#57]
Please, update to 2023.

**Comment by bcheronn** [comment]
Is that package dead?

**Comment by binaryfields** [comment]
Sorry for the lack of updates. I should be able to update the package now and get back to regular updates next month once I have my new development system up and running.

**Comment by bcheronn** [comment]
﻿Hi,

> Le 22 nov. 2023 à 14:48, Sebastian Jastrzebski ***@***.***> a écrit :

> Sorry for the lack of updates. I should be able to update the package now and get back to regular updates next month once I have my new development system up and running.

Thanks for the update and the work you are putting in. I wouldn’t like to move to another IDE 🙂
