### ISSUE TITLE
version 2024.1

### ISSUE THREAD

**Issue by cdock1029** [flathub/com.jetbrains.CLion#69]
Hello, 

Can we please get the newest CLion version 2024.1 update, as the one available in flathub is a few versions behind.

I see the most recent and previous pull requests have failing builds:

https://github.com/flathub/com.jetbrains.CLion/pull/68

https://github.com/flathub/com.jetbrains.CLion/pull/67

Thanks for the efforts of maintaining this package.

**Comment by wwfranczyk** [comment]
I think the build are failing due to missing screenshots (the link specified is no longer working).

I have created a new PR: #71.

**Comment by wwfranczyk** [comment]
Test build available here: #72
